# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/golang:1.14"
    environment: 
      TEST_RESULTS: /tmp/test-results
    steps: 
      - checkout
      - 
        run: "mkdir -p $TEST_RESULTS"
      - 
        command: "go get -v -t -d ./..."
        name: "Get dependencies"
        run: ~
      - 
        run: 
          command: |
              go test -timeout 10s -p 4 -count=1 ./... -v -covermode=count -coverprofile=coverage.out
              go tool cover -html=coverage.out -o coverage.html
              mv coverage.html /tmp/test-results
          name: "Run unit tests"
      - 
        run: 
          command: |
              $(GOBIN)/golint -set_exit_status ./...
              $(GOBIN)/golangci-lint run
          name: "Run linters"
      - 
        store_artifacts: 
          destination: raw-test-output
          path: /tmp/test-results
      - 
        store_test_results: 
          path: /tmp/test-results

workflows: 
  build-workflow: 
    jobs: 
      - build
  version: 2
